### ISSUE TITLE
I can't clone it.

### ISSUE THREAD

**Issue by rqslan** [ITurres/ttm-e-commerce#1]
Basically not too long ago i'd say 2-3 months ago I tried cloning this site because i have a school project and i dont want to fail it, so i cloned it and everything went good but i decided to clone another site. Now the teacher wants another site so i tried cloning it now but it wont work. no watches are on the site its just the home page and the search bar is bugged and i think its because the sections that are supposed to be "auto-injected" arent injected and the site is basically empty. Please solve this issue

**Comment by ITurres** [comment]
Hi @rqslan,

Thank you for opening the issue and for your interest in my project! I’m glad to hear you find it useful.

I appreciate you pointing out the bugs you’ve encountered. I cloned it on another machine and the website seems to work as the deployed version, i.e. fine.

Regarding using the project for your school assignment, I want to make sure you understand the implications of using someone else’s work for your assignment. It's important to adhere to your school's academic integrity policies. While I encourage learning and collaboration, I recommend using the project as a reference or inspiration rather than submitting it as your own work.

Please don't hesitate to ask if you have any questions or need additional help while working on the project. I’m here to help!

Best regards,

Arthur
